In [ ]:
import pandas as pd
import numpy as np
from datetime import timedelta

In [14]:
customer_profiles = pd.read_parquet('F:/iti/python/project/NexaBank45/tmp/2025-05-14/20/customer_profiles.parquet')
customer_profiles

,customer_id,name,gender,age,city,account_open_date,product_type,customer_tier,tenure,customer_segment,processing_time,partition_date,partition_hour
0,CUST000001,Laura Cruz,Female,74,Casablanca,2021-11-29,PremiumAccount,Platinum,3,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
1,CUST000002,Melissa Carey,Female,44,Jeddah,2019-10-31,Savings,Silver,5,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
2,CUST000003,Aaron Maynard,Male,77,Alexandria,2019-02-08,CreditCard,Platinum,6,Loyal,2025-05-14 20:10:19.147663,2025-05-14,20
3,CUST000004,Debbie Reyes,Female,76,Riyadh,2023-02-06,Savings,Platinum,2,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
4,CUST000005,Ariana Foley,Female,31,Cairo,2023-05-07,Savings,Silver,2,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUST099996,Bryan Davis,Female,52,Doha,2021-10-14,CreditCard,Platinum,3,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
99996,CUST099997,Seth Dixon,Male,63,Cairo,2020-04-20,CreditCard,Gold,5,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
99997,CUST099998,Nathan Kelly,Male,31,Abu Dhabi,2021-10-29,PremiumAccount,Gold,3,Normal,2025-05-14 20:10:19.147663,2025-05-14,20
99998,CUST099999,Cory Miller,Female,63,Doha,2017-03-11,CreditCard,Platinum,8,Loyal,2025-05-14 20:10:19.147663,2025-05-14,20
99999,CUST100000,Laura Maldonado,Female,20,Sfax,2017-05-24,PremiumAccount,Silver,7,Loyal,2025-05-14 20:10:19.147663,2025-05-14,20

In [15]:
transactions = pd.read_parquet('F:/iti/python/project/NexaBank45/tmp/2025-05-14/20/transactions.parquet')
transactions

,sender,receiver,transaction_amount,transaction_date,cost,total_amount,processing_time,partition_date,partition_hour
0,CUST000001,CUST090969,68,2025-02-22,0.568,68.568,2025-05-14 20:10:19.396135,2025-05-14,20
1,CUST000002,CUST071246,73,2024-12-20,0.573,73.573,2025-05-14 20:10:19.396135,2025-05-14,20
2,CUST000003,CUST073613,58,2024-10-21,0.558,58.558,2025-05-14 20:10:19.396135,2025-05-14,20
3,CUST000004,CUST016177,28,2024-07-11,0.528,28.528,2025-05-14 20:10:19.396135,2025-05-14,20
4,CUST000005,CUST020449,40,2024-10-28,0.540,40.540,2025-05-14 20:10:19.396135,2025-05-14,20
...,...,...,...,...,...,...,...,...,...
99995,CUST099996,CUST005210,7,2025-04-01,0.507,7.507,2025-05-14 20:10:19.396135,2025-05-14,20
99996,CUST099997,CUST031783,5,2025-01-14,0.505,5.505,2025-05-14 20:10:19.396135,2025-05-14,20
99997,CUST099998,CUST028050,65,2025-01-30,0.565,65.565,2025-05-14 20:10:19.396135,2025-05-14,20
99998,CUST099999,CUST055631,30,2025-03-24,0.530,30.530,2025-05-14 20:10:19.396135,2025-05-14,20
99999,CUST100000,CUST086210,89,2024-06-08,0.589,89.589,2025-05-14 20:10:19.396135,2025-05-14,20

In [16]:
credit_cards_billing = pd.read_parquet('F:/iti/python/project/NexaBank45/tmp/2025-05-14/20/credit_cards_billing.parquet')
credit_cards_billing

,bill_id,customer_id,month,amount_due,amount_paid,payment_date,due_date,late_days,fully_paid,debt,fine,total_amount,processing_time,partition_date,partition_hour
0,BILL3986751,CUST000001,2023-01,48.63,48.63,2023-01-03,2023-01-01,2,True,0.00,10.30,58.93,2025-05-14 20:10:19.762886,2025-05-14,20
1,BILL8030647,CUST000001,2023-02,173.34,144.53,2023-02-08,2023-02-01,7,False,28.81,36.05,209.39,2025-05-14 20:10:19.762886,2025-05-14,20
2,BILL3052310,CUST000002,2023-01,123.82,123.82,2023-01-01,2023-01-01,0,True,0.00,0.00,123.82,2025-05-14 20:10:19.762886,2025-05-14,20
3,BILL4053148,CUST000002,2023-02,51.16,51.16,2023-02-01,2023-02-01,0,True,0.00,0.00,51.16,2025-05-14 20:10:19.762886,2025-05-14,20
4,BILL5685636,CUST000003,2023-01,163.66,163.66,2023-01-06,2023-01-01,5,True,0.00,25.75,189.41,2025-05-14 20:10:19.762886,2025-05-14,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,BILL5817582,CUST099998,2023-02,254.44,254.44,2023-02-06,2023-02-01,5,True,0.00,25.75,280.19,2025-05-14 20:10:19.762886,2025-05-14,20
199996,BILL5523895,CUST099999,2023-01,163.51,163.51,2023-01-01,2023-01-01,0,True,0.00,0.00,163.51,2025-05-14 20:10:19.762886,2025-05-14,20
199997,BILL2060988,CUST099999,2023-02,190.25,180.98,2023-02-08,2023-02-01,7,False,9.27,36.05,226.30,2025-05-14 20:10:19.762886,2025-05-14,20
199998,BILL9535028,CUST100000,2023-01,133.65,133.65,2023-01-06,2023-01-01,5,True,0.00,25.75,159.40,2025-05-14 20:10:19.762886,2025-05-14,20
199999,BILL8590882,CUST100000,2023-02,40.24,40.24,2023-02-02,2023-02-01,1,True,0.00,5.15,45.39,2025-05-14 20:10:19.762886,2025-05-14,20

In [ ]:
transactions['transaction_date'] = pd.to_datetime(transactions['transaction_date']).dt.date
analysis_date = pd.to_datetime('today').date()
last_transaction = transactions.groupby('sender')['transaction_date'].max()
cutoff_date = analysis_date - timedelta(days=90)
churned_customers = last_transaction[last_transaction < cutoff_date].index

print(f"Total customers: {len(last_transaction)}")
print(f"Churned customers: {len(churned_customers)}")
print(f"Percentage churned: {len(churned_customers)/len(last_transaction):.1%}")

Total customers: 100000
Churned customers: 75410
Percentage churned: 75.4%

In [ ]:
customer_profiles['age_group'] = pd.cut(customer_profiles['age'],
                                       bins=[0, 30, 40, 50, 60, 100],
                                       labels=['<30', '30-39', '40-49', '50-59', '60+'])
customer_profiles

,customer_id,name,gender,age,city,account_open_date,product_type,customer_tier,tenure,customer_segment,processing_time,partition_date,partition_hour,age_group
0,CUST000001,Laura Cruz,Female,74,Casablanca,2021-11-29,PremiumAccount,Platinum,3,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,60+
1,CUST000002,Melissa Carey,Female,44,Jeddah,2019-10-31,Savings,Silver,5,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,40-49
2,CUST000003,Aaron Maynard,Male,77,Alexandria,2019-02-08,CreditCard,Platinum,6,Loyal,2025-05-14 20:10:19.147663,2025-05-14,20,60+
3,CUST000004,Debbie Reyes,Female,76,Riyadh,2023-02-06,Savings,Platinum,2,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,60+
4,CUST000005,Ariana Foley,Female,31,Cairo,2023-05-07,Savings,Silver,2,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,30-39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUST099996,Bryan Davis,Female,52,Doha,2021-10-14,CreditCard,Platinum,3,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,50-59
99996,CUST099997,Seth Dixon,Male,63,Cairo,2020-04-20,CreditCard,Gold,5,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,60+
99997,CUST099998,Nathan Kelly,Male,31,Abu Dhabi,2021-10-29,PremiumAccount,Gold,3,Normal,2025-05-14 20:10:19.147663,2025-05-14,20,30-39
99998,CUST099999,Cory Miller,Female,63,Doha,2017-03-11,CreditCard,Platinum,8,Loyal,2025-05-14 20:10:19.147663,2025-05-14,20,60+
99999,CUST100000,Laura Maldonado,Female,20,Sfax,2017-05-24,PremiumAccount,Silver,7,Loyal,2025-05-14 20:10:19.147663,2025-05-14,20,<30

In [26]:
customer_spending = transactions.groupby('sender')['transaction_amount'].sum()
customer_profiles = customer_profiles.merge(
    customer_spending.rename('total_spending'),
    left_on='customer_id',
    right_index=True,
    how='left'
)
customer_profiles['spending_level'] = pd.qcut(
    customer_profiles['total_spending'],
    4,
    labels=['Low', 'Medium', 'High', 'VIP']
)

In [28]:
customer_profiles['is_churned'] = customer_profiles['customer_id'].isin(churned_customers)

churn_by_age = customer_profiles.groupby('age_group')['is_churned'].mean()
churn_by_age

C:\Users\yomna afifi\AppData\Local\Temp\ipykernel_42472\2275769720.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  churn_by_age = customer_profiles.groupby('age_group')['is_churned'].mean()

age_group
<30      0.759888
30-39    0.757600
40-49    0.753188
50-59    0.754294
60+      0.748996
Name: is_churned, dtype: float64

In [29]:
churn_by_city = customer_profiles.groupby('city')['is_churned'].mean().sort_values(ascending=False)
churn_by_city

city
Alexandria    0.760421
Dubai         0.759356
Riyadh        0.757525
Jeddah        0.754432
Doha          0.753148
Abu Dhabi     0.752499
Sfax          0.751218
Casablanca    0.751152
Cairo         0.750998
Beirut        0.750025
Name: is_churned, dtype: float64

In [30]:
churn_by_spending = customer_profiles.groupby('spending_level')['is_churned'].mean()
churn_by_spending

C:\Users\yomna afifi\AppData\Local\Temp\ipykernel_42472\951843647.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  churn_by_spending = customer_profiles.groupby('spending_level')['is_churned'].mean()

spending_level
Low       0.752767
Medium    0.754611
High      0.754997
VIP       0.754042
Name: is_churned, dtype: float64

In [31]:
credit_cards_billing['payment_date'] = pd.to_datetime(credit_cards_billing['payment_date'])
credit_cards_billing['month'] = pd.to_datetime(credit_cards_billing['month'])
credit_cards_billing['days_late'] = (credit_cards_billing['payment_date'] - credit_cards_billing['month']).dt.days - 15

In [41]:
payment_behavior = credit_cards_billing.groupby('customer_id').agg(
    avg_days_late=('days_late', 'mean')  # Only compute average days late
)
payment_behavior

             avg_days_late
customer_id
CUST000001           -10.5
CUST000002           -15.0
CUST000003           -12.5
CUST000004           -11.0
CUST000005            -9.0
...                    ...
CUST099996            -9.0
CUST099997           -11.5
CUST099998           -12.5
CUST099999           -11.5
CUST100000           -12.0

[100000 rows x 1 columns]

In [42]:

# Merge with churn data
payment_churn = customer_profiles[['customer_id', 'is_churned']].merge(
    payment_behavior,
    on='customer_id',
    how='left'
)
payment_churn

      customer_id  is_churned  avg_days_late
0      CUST000001       False          -10.5
1      CUST000002        True          -15.0
2      CUST000003        True          -12.5
3      CUST000004        True          -11.0
4      CUST000005        True           -9.0
...           ...         ...            ...
99995  CUST099996       False           -9.0
99996  CUST099997        True          -11.5
99997  CUST099998        True          -12.5
99998  CUST099999       False          -11.5
99999  CUST100000        True          -12.0

[100000 rows x 3 columns]

In [44]:
# Calculate correlations
# If 'is_churned' is boolean, convert to 0/1 first
payment_churn['is_churned'] = payment_churn['is_churned'].astype(int)
correlation = payment_churn[['is_churned', 'avg_days_late']].corr()['is_churned'][['avg_days_late']]
correlation

avg_days_late    0.003525
Name: is_churned, dtype: float64